version: '3.3'

services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/api.dev.Dockerfile
    container_name: api
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://db:27017/coder
      PORT: 5000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - ../data:/data/db
    ports:
      - 27018:27017
    networks:
      - network
    logging:
      driver: none

  client:
    build:
      context: ../web
      dockerfile: ../docker/client.dev.Dockerfile
    container_name: client
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../web:/usr/src/client
    ports:
      - 3000:3000

networks:
  network:
    driver: bridge
